/*package org.firstinspires.ftc.teamcode; // This should match the file location. This is auto generated by Android Studio
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.pedropathing.follower.Follower;

import org.firstinspires.ftc.teamcode.pedro.Constants;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;
import static com.pedropathing.api.Paths.*;
import com.pedropathing.paths.Path;
import com.pedropathing.ivy.Scheduler;
import static com.pedropathing.ivy.Scheduler.schedule;
import static com.pedropathing.ivy.pedro.PedroCommands.follow;
import static com.pedropathing.ivy.groups.Groups.sequential;



@Autonomous
public class TestPathing extends OpMode {
    private Follower follower; // Add this
    private final PoseFactory p = PoseFactory.degrees(); // add this
    // our poses
    private final Pose startPose = p.of(0, 0, 0);
    private final Pose park = p.of(6, 0, 0);
    private final Pose controlPose = p.of(2, 0, 0);
    private Path park() {
        return curve(startPose, controlPose, park).linear(startPose, park);
    }


    @Override
    public void init() {
        Scheduler.reset();
        follower = Constants.create(hardwareMap);
        follower.setPose(startPose);
    }
    @Override
    public void start() {
        schedule(follow(follower, park()));
    }
    @Override
    public void loop() {
        follower.update();
        Scheduler.execute();
        //telem
        telemetry.addData("X", follower.pose().x());
        telemetry.addData("Y", follower.pose().y());
        telemetry.addData("Heading", Math.toDegrees(follower.pose().heading()));
        telemetry.addData("Follower Mode", follower.mode());
        telemetry.addData("Distance remaining in path", follower.remainingDistance());
        telemetry.addData("Mode", follower.mode());
        telemetry.addData("Following", follower.following());
        telemetry.addData("Distance to End", follower.distanceToEndpoint());
        telemetry.addData("Path Index", follower.pathIndex());
        telemetry.addData("Path Completion", follower.completion());
        telemetry.update();
    }
}

 */
