buildscript {
    repositories {
        mavenCentral()
        google()
        maven {
            url "https://repo.dairy.foundation/releases"
        }
    }

    dependencies {
        classpath "dev.frozenmilk:Load:0.3.2"
    }
}

apply plugin: 'com.android.application'
apply plugin: 'dev.frozenmilk.sinister.sloth.load'

apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'

android {
    namespace = 'org.firstinspires.ftc.teamcode'

    packagingOptions {
        jniLibs.useLegacyPackaging true
    }
}

dependencies {
    implementation project(':FtcRobotController')

    implementation("dev.frozenmilk.sinister:Sloth:0.3.2")
    implementation("com.bylazar.sloth:fullpanels:0.3.2+1.0.13")
}